service: practice-nestjs-typescript

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southest-1
  profile: default
  memorySize: 256
  # stage: dev

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"

custom:
  serverless-offline:
    noPrependStageInUrl: true